services:
  - type: web
    name: resume_scanner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c resumescreener/gunicorn_config.py resumescreener.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resumescreener.settings
      - key: ALLOWED_HOSTS
        value: resume_scanner.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: resume_db
      - key: DB_USER
        value: resume_user
      - key: DB_PASSWORD
        value: secure_password
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 5432
