services:
  - type: web
    name: resume_scanner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resumescreener.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resumescreener.settings
      - key: ALLOWED_HOSTS
        value: resume_scanner.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: 5432
