# Generated by Django 5.1.7 on 2025-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_scanner', '0004_fraudcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
