# Generated by Django 5.1.7 on 2025-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_scanner', '0005_applicant_resume_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='recommended_jobs',
        ),
        migrations.AddField(
            model_name='applicant',
            name='course_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='recommended_resources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
